#!/bin/bash

if [ $# -ne 1 ]; then
    echo "Usage: $0 <github_file_url>"
    exit 1
fi

github_url="$1"

# Check if the URL is in the expected format
if [[ ! $github_url =~ ^https://github.com/([^/]+)/([^/]+)/blob/([^/]+)/(.+)$ ]]; then
    echo "Invalid GitHub file URL format."
    exit 1
fi

# Extract components from the URL
owner="${BASH_REMATCH[1]}"
repo="${BASH_REMATCH[2]}"
branch="${BASH_REMATCH[3]}"
file_path="${BASH_REMATCH[4]}"

# Extract the file name from the file path
file_name="${file_path##*/}" 

# Construct the raw file URL
raw_url="https://github.com/$owner/$repo/raw/$branch/$file_path"

echo "Fetching patch $file_name from: $raw_url"
wget $raw_url -P ~/webpatches/
echo "Applying..."
patch -p1 < $file_name
